# Copyright 2026 The sig-frx Authors. SPDX-License-Identifier: Apache-2.0
"""SHRINCS's stateful address — the specification's Stateful ADRS Format.

The same slots FIPS 205 compresses to ([`../adrs.py`](../adrs.py)): one byte,
then eight, then the type byte, then twelve. What differs is what the two leading
fields mean and what may sit in the type byte.

**The leading fields name a node, not a tree.** FIPS 205 addresses a position in
a hypertree — which layer, which tree within it — while a stateful SHRINCS
signature climbs one FXMSS tree, so the same slots carry the node's height and
its index across that height. The widths line up exactly, which is why the
encoder is shared rather than copied: the eight-byte slot that held a tree
address holds a node index of the same 64 bits, and it arrives as bytes for the
same reason (see [`../bytestring.py`](../bytestring.py)).

**The type values start at 16 and the stateless ones stop at 6.** That gap is
what keeps one key's two signing paths apart: `pk_seed` is shared between them,
so a hash computed on the stateful path must not be reachable as a stateless one
at the same position. Numbering them disjointly is the whole of the separation,
which is why they are transcribed here rather than derived.

**`WOTS_C_PRF` is the one address that carries the tree's shape.** Every other
address here names a position and nothing else, because a verifier reaches it and
a verifier never learns the shape. The secret chain starts are the exception: they
are derived by the signer, who does know it, and binding them to it is what keeps
one seed's leaf at a given position in a balanced tree unrelated to the leaf at
the same position in an unbalanced one. The two bytes ride in the first payload
word, where a chain step has padding.
"""

from __future__ import annotations

import enum

import numpy as np
from frx import Array

from sig_frx.hash import adrs

Field = adrs.Field


class StatefulAdrsType(enum.IntEnum):
    """The stateful address types — the specification's ADRS Types table."""

    WOTS_C_HASH = 16
    WOTS_C_PK = 17
    FXMSS_TREE = 18
    WOTS_C_PRF = 21
    WOTS_C_GRIND = 22


# The `H_grind` tweak is the address's header — the node's height and index and
# the type — and not the twelve-byte payload behind them, which that function
# leaves to its own message. Taken from the layout rather than restated, so that
# a slot moving moves this with it.
_GRIND_TWEAK_BYTES = adrs.COMPRESSED_HEADER_SIZE


def wots_c_hash(
    node_height: Field, node_index: Field, chain: Field, hash_index: Field
) -> adrs.Adrs:
    """A WOTS+C chain step.

    The payload's first word is zero padding where FIPS 205 puts a key pair
    address: an FXMSS leaf holds one WOTS+C key, so the node index already names
    it and there is nothing left for that word to say.
    """
    return adrs.Adrs(
        node_height, node_index, StatefulAdrsType.WOTS_C_HASH, (0, chain, hash_index)
    )


def wots_c_pk(node_height: Field, node_index: Field) -> adrs.Adrs:
    """Compressing a WOTS+C public key into its FXMSS leaf."""
    return adrs.Adrs(node_height, node_index, StatefulAdrsType.WOTS_C_PK, (0, 0, 0))


def fxmss_tree(node_height: Field, node_index: Field) -> adrs.Adrs:
    """A parent in the FXMSS tree — the node this address names."""
    return adrs.Adrs(node_height, node_index, StatefulAdrsType.FXMSS_TREE, (0, 0, 0))


def wots_c_prf(
    node_height: Field, node_index: Field, sf_structure: Field, chain: Field
) -> adrs.Adrs:
    """A WOTS+C secret chain start, generated by the PRF — the signer's address.

    `sf_structure` is the two structure bytes, which sit in the *high* half of the
    first payload word — the four-byte slot FIPS 205 gives a key pair address and
    `wots_c_hash` leaves as padding. They arrive as bytes rather than as the number
    those bytes spell: the value is an identifier that nothing does arithmetic on,
    and writing it as `(shape << 24) | (depth << 16)` would restate the layout the
    slot already fixes.
    """
    return adrs.Adrs(
        node_height,
        node_index,
        StatefulAdrsType.WOTS_C_PRF,
        (_left_aligned(sf_structure), chain, 0),
    )


def _left_aligned(value: adrs.Field) -> np.ndarray:
    """Bytes padded out to a payload word, keeping them at the top of it.

    The one field here the encoder cannot place on its own. Every other narrow
    field is *right*-aligned into its slot, which `adrs_encoding` derives from the
    width alone; the structure bytes are specified at the top of the word, so the
    padding is this module's to add — it is the module that names the slot.
    """
    bytes_ = np.asarray(value, dtype=np.uint8).reshape(1, -1)
    padding = adrs.WORD_SIZE - bytes_.shape[1]
    if padding < 0:
        raise ValueError(
            f"a payload word is {adrs.WORD_SIZE} bytes and this field is "
            f"{bytes_.shape[1]}"
        )
    return np.concatenate([bytes_, np.zeros((1, padding), dtype=np.uint8)], axis=-1)


def wots_c_grind(node_height: Field, node_index: Field) -> adrs.Adrs:
    """Mapping a message digest into the constant-sum space, under a counter."""
    return adrs.Adrs(node_height, node_index, StatefulAdrsType.WOTS_C_GRIND, (0, 0, 0))


def grind_tweak(node_height: Field, node_index: Field) -> np.ndarray | Array:
    """The bytes `H_grind` tweaks with — the header, without the payload behind it.

    The whole rule in one place. `H_grind` is the one hash here that tweaks with
    part of an address rather than all of it, and where the part ends is this
    module's fact, so the slice is here rather than at the caller that would
    otherwise have to be told the header's width.
    """
    return encode_batch(wots_c_grind(node_height, node_index))[:, :_GRIND_TWEAK_BYTES]


def with_hash_index(encoded: np.ndarray | Array, step: int) -> np.ndarray | Array:
    """The same chain addresses at another step — the third word replaced.

    A chain walk holds the node's height and index, the chain and the type across
    all `w − 1` steps and moves only the hash index, so re-encoding each step
    rebuilds four fields that never move. `wots.py` learned this on the SLH-DSA
    verify path, where re-encoding was two fifths of an eager verification.
    """
    return adrs.with_third_word(encoded, step, compressed=True)


def encode_batch(address: adrs.Adrs) -> np.ndarray | Array:
    """The 22-byte encoding, as `[rows, 22]`.

    Always the compressed form: SHRINCS instantiates every hash with SHA-256, and
    the 22-byte address is what FIPS 205 §11.2 pairs with that. There is no
    SHAKE-shaped SHRINCS to make this a parameter.
    """
    return adrs.encode_batch(address, compressed=True)
