load("@rules_python//python:defs.bzl", "py_test")
load("@sig_frx_pip//:requirements.bzl", "requirement")

py_test(
    name = "check_test_budgets_test",
    size = "small",
    srcs = ["check_test_budgets_test.py"],
    deps = [
        "//tools:check_test_budgets",
        requirement("absl_py"),
    ],
)
