# Copyright 2026 The sig-frx Authors. SPDX-License-Identifier: Apache-2.0
"""Falcon known-answer vectors, loaded from the round-3 submission package.

Falcon publishes no ACVP set, so the authority is the one
[`testing.md`](../../../../docs/reference/testing.md) names next: the reference
implementation the standard points at, and the vectors its own generator
publishes. These are those, read from the archive rather than transcribed.

## Provenance

- **Upstream:** `https://falcon-sign.info/falcon-round3.zip`, sha256
  `d625407dbda9e5835f610aaeba1147e029988a6610e0107dfd292033138e1d47`, pinned in
  [`MODULE.bazel`](../../../../MODULE.bazel) as `falcon_round3`. The round-3
  submission is frozen by the NIST process, which is what stands in for a
  commit pin.
- **Fixture:** `KAT/falcon{512,1024}-KAT.rsp`, generated by
  `KAT/generator/PQCgenKAT_sign.c` against the submitted reference code — 100
  records per degree.

**FIPS 206 is still a draft**, so its vectors do not exist to prefer: NIST's
`usnistgov/ACVP-Server` carries `gen-val/json-files` directories for
`ML-DSA-*-FIPS204` and `SLH-DSA-*-FIPS205` and none for FN-DSA. When it grows
one, that set is the authority and this file changes source; the check is a
directory listing, not a judgement.

## `sm` is §3.11.6's aggregate, and the seam takes §3.11.3's signature

The NIST API packs a signed message as `siglen(2) ‖ r(40) ‖ M ‖ header(1) ‖
enc_s`, with a **nonce-less** header of `0010nnnn` — the salt already appeared
ahead of the message. The seam takes what §3.11.3 defines instead: `header(1) ‖
r(40) ‖ enc_s`, header `0011nnnn`, zero-padded to `sbytelen`. So each record's
signature is that regrouping of `sm`, which [`_signature`](#_signature)
performs and asserts its way through.

Regrouping bytes is not the same as inventing them: every byte is upstream's,
and which field each lands in is what the two sections state. The padding is
the only thing added, and Algorithm 18's trailing-zero rule is what makes it
unambiguous.

**One published record has no §3.11.3 encoding, and it is dropped rather than
coerced.** The NIST API's signature is variable-length and the KAT generator
drives the raw signing call, which has no equivalent of Algorithm 10's restart
on an over-long compression — so a record can exceed what the fixed-width form
holds. Exactly one of the 200 does; [`UNENCODABLE`](#UNENCODABLE) names it and
[`records`](#records) refuses to load a file whose set of such records differs
from what is recorded there, so this cannot quietly become two.

## What the records carry, and the two things they deliberately do not

A record carries the public key, the message and the signature — the three
inputs verification takes. Both secrets are withheld from the record itself,
each for its own reason, and neither is an oversight:

- **`sk` is exposed separately** as [`secret_key`](#secret_key) rather than on
  the record, because [`kat.check`](../../../testing/kat.py)'s `_check_sign`
  drives any vector carrying one into `Falcon.sign` — still
  `NotImplementedError` until [#27](https://github.com/fractalyze/sig-frx/issues/27)
  lands its signing loop. §3.11.5's decoder is gated on those bytes today by
  [`keygen_test`](keygen_test.py), which is what they are for.
- **`seed` is not exposed at all.** `_check_keygen` would take it and require
  `keygen(seed)` to reproduce the published pair, and this repo's expansion is
  `SHAKE256(seed ‖ attempt)` rather than the NIST harness's AES-256-CTR-DRBG —
  a decision recorded on [#26](https://github.com/fractalyze/sig-frx/issues/26).
  Reproducing these keys would mean transcribing that DRBG and the reference's
  own sampler and restart order, none of which is Falcon's specification.

So **key generation and signing are not covered by this set**, and that is a
property of what the generator published against what this repo chose to be,
not a gap to be closed later by loading more of the same file.

## Volume is bounded for the per-PR gate, and unbounded for the sweep

The generator gives record `i` a message of `33·(i+1)` bytes, so a published
set is 100 distinct message lengths per degree and nothing repeats. A traced
`hash_to_point` compiles per distinct shape, which is exactly the cost
`testing.md` describes for ML-DSA's set — so [`vectors`](#vectors) takes a
bound and the per-PR gate passes a small one, while
[`falcon_sweep_test`](falcon_sweep_test.py) passes none and runs behind
`slow_kat`. The bound takes the *shortest* messages, which is the cheapest
subset rather than an arbitrary one.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import NamedTuple

from python.runfiles import Runfiles

from sig_frx.testing import kat

_RUNFILES = Runfiles.Create()

_PATH = "falcon_round3/KAT/falcon{}-KAT.rsp"

# §3.11.6's `sm` layout, in bytes: the length prefix, then the salt.
_SIGLEN_BYTES = 2
_SALT_BYTES = 40

# Table 3.3's degrees and the sizes §3.11 fixes for each — the published values
# rather than this module's formulas, since checking a formula against itself
# proves nothing.
_SETS: dict[str, dict[str, int]] = {
    "Falcon-512": {"degree": 512, "signature_size": 666},
    "Falcon-1024": {"degree": 1024, "signature_size": 1280},
}


class Record(NamedTuple):
    """One `.rsp` record, as the bytes its fields decode to."""

    case: int
    message: bytes
    public_key: bytes
    secret_key: bytes
    signature: bytes


def _parse(text: str) -> list[dict[str, str]]:
    """The `.rsp` file as one dict per `count = N` block.

    The format is `key = value` lines in blocks separated by blank lines, with a
    `# Falcon-512` banner first. Parsing it as blocks rather than by regex per
    field is what makes a truncated record an error here instead of a silently
    short set downstream.
    """
    blocks: list[dict[str, str]] = []
    current: dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            if current:
                blocks.append(current)
                current = {}
            continue
        key, _, value = line.partition(" = ")
        current[key] = value
    if current:
        blocks.append(current)
    return blocks


def _signature(sm: bytes, message: bytes, name: str) -> bytes | None:
    """§3.11.6's `sm` regrouped into the §3.11.3 signature the seam takes.

    `None` when the record has no §3.11.3 encoding at all — see
    [`UNENCODABLE`](#UNENCODABLE). Every other check here is a claim about the
    two sections agreeing, and each would fire on a set that parsed but meant
    something else: a wrong offset yields a plausible-looking byte string that
    rejects everything, which is indistinguishable from a broken verifier.
    """
    degree = _SETS[name]["degree"]
    logn = degree.bit_length() - 1
    siglen = int.from_bytes(sm[:_SIGLEN_BYTES], "big")

    salt_end = _SIGLEN_BYTES + _SALT_BYTES
    salt = sm[_SIGLEN_BYTES:salt_end]
    body_start = salt_end + len(message)
    if sm[salt_end:body_start] != message:
        raise ValueError(f"{name}: `sm` does not carry `msg` where §3.11.6 puts it")
    nonceless = sm[body_start:]
    if len(nonceless) != siglen:
        raise ValueError(
            f"{name}: `sm` tail is {len(nonceless)} bytes against a stated {siglen}"
        )
    if nonceless[0] != 0x20 | logn:
        raise ValueError(
            f"{name}: nonce-less header is {nonceless[0]:#04x}, "
            f"not §3.11.6's {0x20 | logn:#04x}"
        )

    encoded = nonceless[1:]
    padding = _SETS[name]["signature_size"] - 1 - _SALT_BYTES - len(encoded)
    if padding < 0:
        return None
    return bytes([0x30 | logn]) + salt + encoded + b"\x00" * padding


# Records the generator published that §3.11.3 cannot express, by `count`.
#
# The NIST API carries a *variable-length* signature and the reference's
# `crypto_sign` writes whatever `enc_s` compresses to. §3.11.3's form is
# **fixed** at `sbytelen`, so it holds at most `sbytelen - 41` bytes of `enc_s`,
# and Algorithm 10's signing loop is what keeps a real signer inside that — it
# restarts when the compression does not fit. The KAT generator drives the raw
# API, which has no such loop, so a record can exceed the bound.
#
# Exactly one of the 200 published does. Falcon-1024 `count = 82` compresses to
# 1240 bytes, needing 1281 against a `signature_size` of 1280; Falcon-512's
# widest is 619, needing 660 against 666. It is dropped rather than truncated or
# padded differently, because there is no §3.11.3 byte string that means it —
# the seam's `verify` takes a `signature_max_size` array and this record does not
# fit one. A test pins this set so that a source change cannot quietly grow it.
UNENCODABLE: dict[str, tuple[int, ...]] = {
    "Falcon-512": (),
    "Falcon-1024": (82,),
}


@lru_cache(maxsize=None)
def records(name: str) -> tuple[Record, ...]:
    """Every published record at one parameter set that §3.11.3 can express.

    In the file's own order, minus [`UNENCODABLE`](#UNENCODABLE).
    """
    path = _RUNFILES.Rlocation(_PATH.format(_SETS[name]["degree"]))
    if path is None:  # pragma: no cover - a packaging error, not a case
        raise FileNotFoundError(
            f"the {name} known-answer file is missing from the runfiles; "
            "the test target needs `@falcon_round3//:kat_vectors` in `data`"
        )
    blocks = _parse(Path(path).read_text(encoding="ascii"))
    if not blocks:
        raise ValueError(f"{name}: the known-answer file parsed to no records")

    out = []
    dropped = []
    for block in blocks:
        message = bytes.fromhex(block["msg"])
        case = int(block["count"])
        if len(message) != int(block["mlen"]):
            raise ValueError(f"{name}: `msg` and `mlen` disagree at {case}")
        signature = _signature(bytes.fromhex(block["sm"]), message, name)
        if signature is None:
            dropped.append(case)
            continue
        out.append(
            Record(
                case=case,
                message=message,
                public_key=bytes.fromhex(block["pk"]),
                secret_key=bytes.fromhex(block["sk"]),
                signature=signature,
            )
        )
    if tuple(dropped) != UNENCODABLE[name]:
        raise ValueError(
            f"{name}: records without a §3.11.3 encoding are {tuple(dropped)}, "
            f"where {UNENCODABLE[name]} was recorded — the source changed"
        )
    return tuple(out)


def secret_key(name: str) -> bytes:
    """The count-0 record's `sk` — §3.11.5's decoder gated on published bytes.

    Beside the records rather than on them, for the reason the module docstring
    gives: a `secret_key` on a `kat.KatVector` drives the shared harness into
    signing that does not exist yet.
    """
    return records(name)[0].secret_key


def vectors(name: str, limit: int | None) -> list[kat.KatVector]:
    """One parameter set's cases as the shared harness's record.

    `limit` keeps the first `limit` records, which are the shortest messages
    because the generator grows `mlen` with `count`. `None` is every record —
    what the sweep takes.

    It has no default on purpose. Every caller states the volume it is paying
    for, so a bound is a decision in the reading rather than one inherited from
    here — `testing.md`'s point that a gate which quietly stopped exercising
    something reads exactly like one that got cheaper.

    `valid=True` throughout: every case here is one the reference implementation
    accepts, which is what the harness's derived passes need as their starting
    point — a moved bit is evidence only against something that verified before
    it moved.
    """
    chosen = records(name)[:limit] if limit is not None else records(name)
    return [
        kat.KatVector(
            case_id=f"falcon-round3 KAT {name} count={record.case}",
            parameter_set=name,
            public_key=record.public_key,
            message=record.message,
            signature=record.signature,
        )
        for record in chosen
    ]
