# Copyright 2026 The sig-frx Authors. SPDX-License-Identifier: Apache-2.0
"""Falcon known-answer vectors, transcribed from the round-3 submission package.

Falcon publishes no ACVP set — FN-DSA is still draft — so the authority is the
one [`testing.md`](../../../../docs/reference/testing.md) names next: the
reference implementation the standard points at, and the vectors its own
generator publishes. These are those, and being transcribed constants rather
than a fetched file they carry their provenance here.

## Provenance

- **Upstream:** `https://falcon-sign.info/falcon-round3.zip`, sha256
  `d625407dbda9e5835f610aaeba1147e029988a6610e0107dfd292033138e1d47`. The
  round-3 submission is frozen by the NIST process, which is what stands in for
  a commit pin.
- **Fixture:** `falcon-round3/KAT/falcon512-KAT.rsp` and
  `falcon1024-KAT.rsp`, generated by `KAT/generator/PQCgenKAT_sign.c` against
  the submitted reference code.
- **The exact call each value came from:** `pk` verbatim; `msg` verbatim; and
  `signature` **rebuilt** from `sm`, which is the one value that is not
  verbatim and is described below.

## `sm` is §3.11.6's aggregate, and the seam takes §3.11.3's signature

The NIST API packs a signed message as `siglen(2) ‖ r(40) ‖ M ‖ header(1) ‖
enc_s`, with a **nonce-less** header of `0010nnnn` — the salt already appeared
ahead of the message. The seam takes what §3.11.3 defines instead: `header(1) ‖
r(40) ‖ enc_s`, header `0011nnnn`, zero-padded to `sbytelen`. So each vector's
`signature` is that regrouping of `sm`:

```python
siglen = int.from_bytes(sm[:2], "big")
salt, message, nonceless = sm[2:42], sm[42 : 42 + mlen], sm[42 + mlen :]
assert len(nonceless) == siglen and nonceless[0] == 0x20 | (n.bit_length() - 1)
signature = (
    bytes([0x30 | (n.bit_length() - 1)])
    + salt
    + nonceless[1:]
    + b"\x00" * (sbytelen - 41 - len(nonceless[1:]))
)
```

Regrouping bytes is not the same as inventing them: every byte below is
upstream's, and which field each lands in is what the two sections state. The
padding is the only thing added, and Algorithm 18's trailing-zero rule is what
makes it unambiguous.

## Two cases per degree, driven through the shared harness

`vectors(name)` hands them to [`kat.check`](../../../testing/kat.py), which owns
the published-verdict pass, the tampering pass and the replicate-and-tamper batch
axis. None of those is Falcon's to re-derive: `testing.md` puts the batch-axis
gate in the harness precisely "because the gap is a property of how the vectors
are published, not of any one scheme — a per-scheme fix would be written once per
scheme for one cause."

`seed` and `secret_key` are absent **from the records**, which is what makes a
verification-only scheme drivable: `_check_keygen` skips a vector with no seed
and `_check_sign` one with no secret key, so neither reaches the
`NotImplementedError` that `keygen` and `sign` are until #26 and #27.
`eddsa_test` is the precedent for inline records rather than a loaded file.

The published `sk` bytes are here all the same, as `SECRET_KEYS` beside the
records rather than inside them — §3.11.5's decoder is #26's and can be gated on
them today, where putting them on a `Vector` would drive the harness into
signing that does not exist yet. Reproducing the published *keys from their
seed* stays out of scope for a different reason, recorded on #26: it would mean
transcribing NIST's AES-256-CTR-DRBG and the reference's own sampler, neither of
which is Falcon's specification.

What these two per degree buy over one is that a fluke cannot carry a degree on
its own; the batch axis is not gated by them, since the generator varies `mlen`
per case and grouping published cases yields only `B = 1`.

**[#28](https://github.com/fractalyze/sig-frx/issues/28) replaces this file**
with the whole set fetched and sha256-pinned as an `http_file`, which is what
the convention asks for once there is a loader to justify it. Until then the
transcription is small enough not to tax a clone and complete enough to gate the
assembly.
"""

from __future__ import annotations

from typing import NamedTuple

from sig_frx.testing import kat


class Vector(NamedTuple):
    """One accepted verification case, as bytes in the standard's encodings."""

    # The .rsp record's `count`. Named `case` because `tuple` already
    # defines both `count` and `index` as methods.
    case: int
    public_key: str  # §3.11.4, `public_key_size` bytes
    message: str  # the `msg` field, verbatim
    signature: str  # §3.11.3, `signature_max_size` bytes, zero-padded


VECTORS: dict[str, tuple[Vector, ...]] = {
    "Falcon-512": (
        Vector(
            case=0,
            public_key=(
                "096ba86cb658a8f445c9a5e4c28374bec879c8655f68526923240918074d0147c03162e4"
                "a49200648c652803c6fd7509ae9aa799d6310d0bd42724e0635920186207000767ca5a85"
                "46b1755308c304b84fc93b069e265985b398d6b834698287ff829aa820f17a7f4226ab21"
                "f601ebd7175226bab256d8888f009032566d6383d68457ea155a94301870d589c678ed30"
                "4259e9d37b193bc2a7ccbcbec51d69158c44073aec9792630253318bc954dbf50d150282"
                "90dc2d309c7b7b02a6823744d463da17749595cb77e6d16d20d1b4c3aad89d320ebe5a67"
                "2bb96d6cd5c1efec8b811200cbb062e473352540eddef8af9499f8cdd1dc7c6873f0c7a6"
                "bcb7097560271f946849b7f373640bb69ca9b518aa380a6eb0a7275ee84e9c221aed88f5"
                "bfbaf43a3ede8e6aa42558104faf800e018441930376c6f6e751569971f47adbca5ca00c"
                "801988f317a18722a29298925ea154dbc9024e120524a2d41dc0f18fd8d909f6c5097740"
                "4e201767078ba9a1f9e40a8b2ba9c01b7da3a0b73a4c2a6b4f518bbee3455d0af2204ddc"
                "031c805c72ccb647940b1e6794d859aaebcea0deb581d61b9248bd9697b5cb974a8176e8"
                "f910469cae0ab4ed92d2aee9f7eb50296daf8057476305c1189d1d9840a0944f0447fb81"
                "e511420e67891b98fa6c257034d5a063437d379177ce8d3fa6eaf12e2dbb7eb8e4984816"
                "12b1929617da5fb45e4cdf893927d8ba842aa861d9c50471c6d0c6df7e2bb26465a0eb6a"
                "3a709de792aafaaf922aa95dd5920b72b4b8856c6e632860b10f5cc08450003671af3889"
                "61872b466400adb815ba81ea794945d19a100622a6ca0d41c4ea620c21dc125119e37241"
                "8f04402d9fa7180f7bc89afa54f8082244a42f46e5b5abce87b50a7d6febe8d7bbbac926"
                "57cbda1db7c25572a4c1d0baea30447a865a2b1036b880037e2f4d26d453e9e913259779"
                "e9169b28a62eb809a5c744e04e260e1f2bbda874f1ac674839ddb47b3148c5946de01801"
                "48b7973d63c58193b17cd05d16e80cd7928c2a338363a23a81c0608c87505589b9da1c61"
                "7e7b70786b6754fbb30a5816810b9e126cfcc5aa49326e9d842973874b6359b5db75610b"
                "a68a98c7b5e83f125a82522e13b83fb8f864e2a97b73b5d544a7415b6504a13939eab159"
                "5d64faf41fab25a864a574de524405e878339877886d2fc07fa0311508252413edfa1158"
                "466667aff78386daf7cb4c9b850992f96e20525330599ab601d454688e294c8c3e"
            ),
            message=(
                "d81c4d8d734fcbfbeade3d3f8a039faa2a2c9957e835ad55b22e75bf57bb556ac8"
            ),
            signature=(
                "3933b3c07507e4201748494d832b6ee2a6c93bff9b0ee343b550d1f85a3d0de0d704c6d1"
                "78429513090765843d1e460d17a527d2bca405bd55bbc7da09a8c620be0af4a767d9db96"
                "b80f55e466676751eaaba7b93b86d71132daa0eb376782b9eee37519ce10fdd33fe9f293"
                "12c31d8736206d165cf4c528aa3ddc017845e1f0dd5b0a44ff961c42d874a95533e5b438"
                "982f524ca954d87533bfbe42c63ff2abc77a34c79db55a99171bbcb72c842a6530af2f75"
                "3f0c34ac632f9f1e7949f0bf6c67665b27722a8857d626b6ff1a136d923a39f4069b7477"
                "ff946e5247a6627791d49b59edc9e2525a860e6e9828d18f64a9f17222e8166a02453859"
                "bbda0b8186d8c9928bb571e4146401d7430e225904673ad21ccac54c146c248a1dd69ab6"
                "491e901d6d71b152155be97de057f3916a3f1b4273308c29b2f4d9697167b90681b1583e"
                "d930a71e990467dea368134beceebd597f9bec922e816f1b0570d728f4ae0464c1f79765"
                "7f87a4e52dcdcaeb9272662ea66d7c6cd8781b31af555ad93f5f65e75816cb8dc306bb67"
                "e592b5261baca7c509629ea2af8abb80cba89ee535b76dfd9ccbbe3bf48f2bc8aa34b26e"
                "1103291053f5cb8de3a45afa5a76df8b2122ed2c82fbcf2259290d41a14f86b12f35f5d4"
                "9762b34cff13ee7e42edec70201d7f37c33316288fa3078e36e58108865c3cfe263d5636"
                "92043decc62f3426f86061285b7b1b336f56ff41bb65e9cd6d9b92fd90f864aa1c923cb8"
                "c755f5cde1770d862595427149d7721aaab5d194aea9acdeca15be43cba6a62b5a33909e"
                "9fc4da1c5814fbd7cd6a2fa572e318b42c6c319140b86e66392580a11a2b431f44c1f927"
                "0e4f7b2490f3b325a9977a71a575915636635b9969dbd6d220b24c3d99cebbbd834b8822"
                "2bd08c3abe124e8000000000000000000000"
            ),
        ),
        Vector(
            case=1,
            public_key=(
                "09baccc8d6c916c9ad12e3e49881f732b84870ce5976921d197a00d226ab8825430da78f"
                "19b0e7a12129ecb739d4a05c5ebb0019f0c610e14556a0b4c7a48e2e4cc851d2e8a57417"
                "e48f918b56dc605d25113451c3b10520f81c016a63c6f2d8826b90b04d8b0a792272607e"
                "39829adf4b09c0cafb11cf2f893c56b26420f84901ff072f9100013536822d512792643d"
                "f4ede4b64200ae0bf82b7d46792eeae3571f501a9a814e69f21e84dc263457b913957886"
                "af9da2598003e853ac23b4d682971507b85bfeb146010b4b0cdd3f00af806cbd56a32987"
                "e38532ae3c7794058215c5db042026ac7dfa58ea5b17b8ae91e06a07db253e21eff361ec"
                "063412b227fe2cf9592c6b4888589f0a3a7fb9a300b131fc4ae755ce16a1554be6ce0f4e"
                "8301bb814e2d1903a209f0744687024949876ac94187fce08655c2131f2a448864cd6c77"
                "783ea2de6c1042c68e389f6d068eec2199dc9b6e92edd4469a923a683ab1c49557c19d9c"
                "c9a3822b628862a9e5df2b152f898172f3c5fda506c2b21e10ed39cc1cebf50b889c493e"
                "1b6614a53c30ee7be94abe59d83c270350ad490e2f9205e5607ae9328322c60aacacea9a"
                "f2a12114626964b68af104aa3b34c1a9e0ae1885314891710b3ace65f54f40451abe425f"
                "d7af4218ffd067a2f61e32d851831aab032c0fa95bcc5504fcf8c180a9ea6d14cb23e35d"
                "f931c40766468487612a172575d0ba6f20c225ab82a562f0eef6d20ed239da08287dde67"
                "701d2c29368dbe52acbbe0f219200535add286e6eb88e4f1643e922b2accbe8a3b52737a"
                "60a4344544966e66b7da65657b5bde6343b5987111c6863446c04415e0d985ab534e1d7e"
                "ac615dc08e8f3d2a73d6057418368ad1dfa7001e647876cd50d589765695cf9715739e5d"
                "42fa684c51c9077a95e7eb31b87ba1808882b0cd9fa0f5d4f26d596af17f22dd09c18836"
                "106f5979203b01d10707840c80249f9b963080fd5221c250ae405f5a5d0c312b6ea8971a"
                "998324c542323808cc9a81a42aa9df3c9080bcb4cf5bd73dfe5c080ceaaa66e0fae05d88"
                "f23b76732ba4094c2d30fd16d26ac4247291fa2543b7751eff202113588b76a1646ecc6a"
                "a17861db54d5adbbfd3ae11423f3a78e8342deee705e98bf8bda82731a520374c69c6593"
                "c5d755c498f7b454c0185758c94b580d4257d66f71ead38205e2cc717032f18656496424"
                "72c5f34e1854040c63369c8317c1fc37518b16637840a86627113e3809a700cc1b"
            ),
            message=(
                "225d5ce2ceac61930a07503fb59f7c2f936a3e075481da3ca299a80f8c5df9223a073e7b"
                "90e02ebf98ca2227eba38c1ab2568209e46dba961869c6f83983b17dcd49"
            ),
            signature=(
                "3908e25538484cd7f1613248fe6c9f6b4ec14be684c6defdd1e41333b6e9052ac4340e31"
                "4eea2c99f7e62b31023eb236b557957f7174885220923a7763217d9fe59b5ba53157ced5"
                "1cd4d9ab93b38c666d2047c4fa21aee43c95ea373f6d62f0e044bdb0be988685154ef768"
                "2617c7367b30d934b1d9c89229d281734a3005124b8d7c70b78e1634a3a20ccf9ab952c8"
                "16dfad3d173567c139bdc624512f23f2a0c2f78c2be16d8f9b119d64ba6dec5e50ad104d"
                "8ba25edc9e53996f75d848caa0e4421167dd4d42d07d39c3e35d10924c1a8a9e098aa4d6"
                "112c67dbbf08c7a0888aeb657456c19e2259621edc3af8978de9c429b8167e679687a86c"
                "bb66403fbc6ee69f3f1344d07e845a865f22e5e94d9748cc12065fe1926d83cb288918c8"
                "2d19fd5416de27576df8e45de1bd74351d996514748ae9018d27f57edb1de46975feba5e"
                "6d9bb1491c2a327bf158d03d2fbe0882ee0adc9b8121876dd9ef5c37f58d325af59b94df"
                "324cce5bc1216c8f4ecd0b4bb5728f83beeab09bfe3966cebdf4657ec6cfd773f0d5dba5"
                "bf28481dcb21aa1984e9c6d2168e350b4d6491d81967be0e354c869a8487f0f939f537a5"
                "8df88abf2e4fadb55250897a54a8475d160d697a77da36bbb1438245b35dee2ac791920c"
                "9fad8025adc8dfa88b168716c5a45075a3f9536bce6238e1ad4d41995d675d3cb71ad4ce"
                "33d0326ec2a9f5b9c1dc6750ecaa6aeaad4c0edcc4a5015eb3f7503ba2210b16665f889e"
                "4d1cf3a9e298d61b23846593fd4d772c646dd024823371d531094cbb17902db113796852"
                "161f5d2a12608b3c1bcece960aad07952671e4cd6186b7ecfbc7710258b8b26cfa3f1cec"
                "c61121a49dd276e4b124e3573ac8231b60c778e03b74926e2bfbecd42f352bc325cf2204"
                "b3c0b5730e6188cfc0000000000000000000"
            ),
        ),
    ),
    "Falcon-1024": (
        Vector(
            case=0,
            public_key=(
                "0a0441a9b73f494d16556680b12b0f446a652700e4304151bc310683c43f20ab28492ff5"
                "80708068fa064275c1b0d08452fc7c324154929ca850d4e6f3425b0f149475a14468c740"
                "be9842d2c1bbb93e2001f4202068d060c1aa9f99a5f67e86800f2e2a48fce95a1e9f570a"
                "12d4a11b22acb86716fb6ebb45b6ce1020e7f44e4230103713ec346055d407c969605d9f"
                "76cb8b2f0af2bbe1ac1f4a278009266fdeea0afada2598e36a492e0b40eae12539a4b1e4"
                "4d150d47c192d9895ca08d1e91d24e535c6d6490038c629045917508ca815e14f401f4a9"
                "a5c15e011204d012d0bb71876abd5a8c75a94f32fe0628289db4664a96b45e494d2528ea"
                "90781a3098e8dad76fd583a890efefae861e815dc26894ec5965fe8f389c14ecd77b2032"
                "7c44b202cbde2b4566b9f73a022fa0641bf81caab70e822065b61f5e9fc919238deaf80b"
                "a4c1726dd50c642e39dada13ec8935e9936a95766ffdf868c4d95db2c1a67097225c464e"
                "faa8de05d806bc5e47f79643180142d5ef53a88e7e06c364a598779c04830b08e6910495"
                "f9938af193ac54970fed8db696001256451f91396c67f1a90f8d5d51ba9ca90b217a8f27"
                "dc844096448f75b12c428bd0ff2984600f95b9d601cecaf967c6a062a399ab1fb67da110"
                "239e739e6195a811459f21b4570f6c077df858550c4fed907240442accfe5195bef68c2c"
                "95756e889378d05f7ede7223ae27618d6a91105e8c6492d9acb30526aca35976343fd46c"
                "1284a4675854bb44e9dceb32499ea6a4f452dd59400bf096175b060c15e5ed501bebb24a"
                "9c0ca96dd5f348f66e27488df0b8954569e46b96a409adb2d1ace23889e17aea253288c5"
                "45f48b82c12b2956e09c008d455c93145f638348502314eb271d924ced3b4f5e9fbd3d10"
                "b3cea6778b506121140ee25414ec56a5ce057a2422ea74c0a021352822e7643663644731"
                "7a121d4afd2541008a997b15f3a298de7587aadc903ba644a859ec40a3d8d75254cba581"
                "217380f95c33a4d514b946cb573a50b819f8702a35029645b008eb08def18552e706f4ef"
                "f147c93b683dedbd6a7ca4183bd2f5ab3890d5b32c4780be2054eb151d182d54a502576f"
                "395899c6d548c916b4bd058e116243887d56c462a9a616abe28204ed5a1a3239c9859264"
                "513b02c11f0c30c976c1f6825bb152e8d4a42129a73137031724322322b7928664c32cac"
                "d0da7a29fc87c808a2a0ce9194424b077c1eef54355f03f50a870889868275dbd5268c53"
                "b2c9854bbb69ff12f75d113438df3a6f129754ca7622b066ed5b4564266ce011a5804b7b"
                "e1c5e24de1e1719848936a9978c0148f08b2e610090c99585d323695aada1a335a7590f7"
                "ee501f284df5fd1c757e4c9b92eaaf737f20026b299351350c8aa8c1060d7861315012c5"
                "20118e27ea0890ca774205145ee7244c811ed0d2a9cf9accc3c5a01c94b480cbd2b41fb7"
                "b501850944c2c489089eea9ec6639c9a1139b756c40ba120fada904c7c06772a131858ae"
                "2986c2278e5126215e631591505ef1ff281e201bbd149d7aaca2926d8cbb2729aa9977e6"
                "79f5de62a138edfc9ad11f09a984e6704e5caf3f6451010ed3dab5e0d03573187543fcc6"
                "7aad6d86bb56138306de7981ee4c676b19a0acbda017fb14014b1e0bd4cbd989a50a9d03"
                "ef21f75db63104ef07c04f9476167d47eca3104517bf8dc00b018f9178437c6810e715ae"
                "603684755054649e5f8eba2b337c28ae377674f12b02b4285cc9d1ec1f459ae88dd4486f"
                "30a8fc7fe3d5a6ac84a6db056d05dc035de1cb29890b74d05ef4432de4516c0983fe1965"
                "a001d737c7de2d885dd3d636e1b7898c9ecb6a9ea7a6a15b4a18d2a1a0f4c877ec01930a"
                "75223368a82a22b50a7681d88970de12985f987865f5a5898cd52370123d638aeab37829"
                "b5abb1da8c2989ee532ae538535973b022491033167d51c46a06b6e17c3183eca65b7515"
                "f865d5308ffd8d698555525cf6d79653597f4e46d126e6d67f142519f1410adc69589b23"
                "165d0f87eac5f7de4f3c13d14b643b608a32d980d125567e9cad1eb095c4c4bb05d5a9b1"
                "eecc3e9aad4174182841f1e8c62204116e719ff3474e4663ada986dca08c350162298b48"
                "8baaddb3761d25ce5114fab64c979e5fcdae6a024ef7a80679a2415aac324408232363d1"
                "2285dd33a690b3205175e6c75a85b368f8b1fe5bbb02eafa624c61938bc2f805e94d001a"
                "aa90e6a2ee8852f82b573d09524daed64933a03918c87e03bbc5f9a4349308666e83318c"
                "968a8486c8a722b1398c8429a9819a7bf5095739969c03beadf7937a5dfa16dc7c44a8e3"
                "d355900a7d4089a5d300bb690cd8633b4de36670d9374997a0309e117630131cb269f4b1"
                "ef9ef12980c0f3f40e6423c547b8c142a04d4d54a0054262776887358861228d1052d9f9"
                "60a877f89e0b8768c307c687a683941fa9a473110f87966cb56a81af94c98c614740c945"
                "3999a6d0d3b12de361ad7375ebd3022dc2b7626a286a63b8448947cacc"
            ),
            message=(
                "d81c4d8d734fcbfbeade3d3f8a039faa2a2c9957e835ad55b22e75bf57bb556ac8"
            ),
            signature=(
                "3a33b3c07507e4201748494d832b6ee2a6c93bff9b0ee343b550d1f85a3d0de0d704c6d1"
                "7842951309b49a5b21696c895463eadc68be13293ef2bb36368d1f916edd6deddd17ed7f"
                "27061e61e54a91928d34d8fddb65af422cd36c2c912c51919d278d39c3596dc619474032"
                "10a9eb974569b35abed194889844a36705e7e73f979f9e6ffbb2e211bf5242a9a31e26d5"
                "011bc2d6c919ee34ae048cac9aed4d2661688f426d167f1b6c608876158c96a5538bce7e"
                "7a46aaa90a28c1cda418ce8fd25e6a2c348fde2584199f77355c4defdba4a1bdf4ecb9da"
                "f632527e629718ddcb7173480a0543359ceee8e40f9919122859b889a60a3ebe91276149"
                "0b8a5ef952ea093252acf2a90282e96186ddcd283c8b6639ca665902598126720e38d1d9"
                "a9e22026d02e6422169740b57574691d2f349f46e5a062f2af0d7b5f366f70b95e2b2152"
                "7b25117e4486d79c20a508a029594ae10643a8d7cd6c60cbc998836e8d4a850f358efda4"
                "c4e902ef7ca7d4c4ba9e44f6d5afd78ada910f51849a98f6cb4f02510cbab3d1573656fd"
                "150984dc14e9b33fbfdafe4c39a58bc3bfd9af7e8fa6ddf47c5eb9ec5efc99bad9e5f208"
                "6b6c593b3e249d6d63a886816e33f6691e631ce253cbcaacceadcafe6fa73ad9e84d89c7"
                "2199448ea2d092b4ae3186cfed4ae763450851b14eb448c9103468bd50a42e56692274aa"
                "dcd112495414713e77c9d3e510290dd13d8c6f39ebd6f12ac4b61cd8141d0467ee8d2abe"
                "5b706cab1ac7e598bc56fce445b6de7a4cf329a4ad2e6aa67fd1c9f4bbcffc6f898fe56d"
                "ccfc43e2d0279ac7cc872f1961fe86b76a4a8297b4f296dd0a4258b79b47b35fcedaf2e2"
                "411b6c0120a2a47916b24121e3d321c4fd212e54caaf2daa4e743d13bec4769eb489ad82"
                "fca56cde2449c91dbbd4d8cd27689d2f775b26291429e79e1df4f385a94fafd834c8b523"
                "850bf7b770542d6e21af3bc288645c39dfdbcb85679b2e3360816d5ec246e6d00ca3965f"
                "4afcee8a93cdd83353127de19376f86490542a325954c9218cfcdc3e3f9ce3443bdfb3ca"
                "c8aa2cdbfe976638478d284c5ad67abb3b857f994b7648cfa9adfb6305d94a51665a989a"
                "69f2df6a4604ffd5a49646c22da9e46ac880ffd1b7587cd9a896bae2caa66aa9fb246656"
                "31ae7b48c6b1cd02cfc4b1f274f00745219b77589b165c8518135beda3ed7931de7a358c"
                "fb3230762b827fe5258715488238338b4a3f1870cce759549cc54a743650936fb0f458e2"
                "0dfbe89a2a5d67c520699d3e4ad6e2ce1708c49109d671d999a5337798ae5de53033956b"
                "982430589dcef30fad98618f572976ea4166cc2adc0b16f6551c6a5c37830be98215ea8a"
                "2e97253e2956711d4de13fafd141843bbc28a8d44bcbfd523d9aa6405588ec09ce435a68"
                "44df0b8268b43907b578b61f4c4c6562a1b56e9a1b74d3d17529812b94f49d98b42dd34b"
                "9f0e9c7125137d3cbd326ca35385313f5196edc697b9bb204ae4298ddf9f2861b3f445fe"
                "c6a8fb6a8c2cfc711178b9864f320e4e108964ed1cb6ee94aef722faae36a68bc4bda304"
                "39515794f881a397bd782a5432218d2531262ec6b5610de3d56b47de5fca82c1251a6662"
                "21cd747bf90d1e57fbae4920ddea69a84320bdb9cb325fe3ab12f97d903085070e9fc2a0"
                "5489f336c433cf970d937235152eca89548ee551af8f421948c2561f07f3ede6bcb9db4a"
                "ac15148862bb6659f6d7a15438f39881248f2bc7ad397801b89446f6cddd62fe56696c7c"
                "bc6473e95a8d03c573e000000000000000000000"
            ),
        ),
        Vector(
            case=1,
            public_key=(
                "0a3d148e18fc1c313afead62e4ddaf6399f6ba5c46f18fed739552cc6145012b8347d5b7"
                "4e5c1b1194d78ca6c981e782075aab0a8a46c6863347a643bbd60b13a8d4e743a258eb9a"
                "cc3d1b5d514d9be217634846266d363417bae98c07114618d4cdb77834d28520c98c941c"
                "bf9a05acd202fefcc11c6729387171b22dc3daab6810919e575cb1de6b0a39ad4a9776d4"
                "190a903bade1fbc1fa44519b951cc62d6d567e6d7071b6c8a782455d86bcc09570262db5"
                "ebc4e7b7716d4a0a9108542d628b16863f7ce1d143e2453b2e6c001bbf8f4778d263850c"
                "66ea4d75dfd6475cec58149f48489d108329ae96c78a7f6d86ba641da8c812719d5acda8"
                "e604c64c46d3adf314e264c7b3e7f217d5237b55a465af14e582e9c5de479dc3d98e1447"
                "5ac67f96d18d973f4113abf986110eb5f5b34141d1b82ad5ab28aeea7c5e06c123042953"
                "b079f546265d9d2d3e84e8aa0d3c248aebd5d355108011e193c0e870024eaa4617ef2175"
                "16327aa68c0312baaaf0c1fd2e9aa75be34fba6e958194decc6a677abb7793a5cbaed9a0"
                "a8fd01d012cac0a5b22ab4b3383e4b20d27a902228531febb482a24a5b090c020bf5ebf9"
                "3ce36a1bee44eb7bc0119cbc2b43b25adb6dc02e6aa7e7653e247dc9cfeeed265c070153"
                "92ff40324a947f2305926e99c8f7a45d18481655dde7e0b002d8d2702eeb3d567e596089"
                "a16a2df352e543bb260c77e1eea285135a11d101a49e1b86770a34abf08e25b7a7e4c923"
                "8c841690e3d8e195b560b3d65b9027fe74c632001c0f35f124ed419443f145b95d1bf27b"
                "f276378a69dc1c98ba25e8ec6e4ca25b584a8708b35266171ea58b55099626ab02ff0349"
                "9c578ba2a85be127bbf9533b1478c3281c9c27a56dd6fa50c0973e0c3e43892bb98002e7"
                "147201c02d944147f0e7a463297e77fea89c1d3949348143e40bb1da8afc94f7b1f13277"
                "019800908d3b8150d3146ac0e5771c26e8300c03b67d51dbb4b65626a352ae19625ff560"
                "2dc2a8dc8ae67dab730fda2813202bdfa42cf4a48b8f6218bcab760bd96145f479aa4eda"
                "f69b2073014e1a737f9942010f9a5581f112d44d5f089a1cbe0a755a3ab08e66e9111591"
                "101ddb5636914bad223b383c02db81bd07f4c7d553466d20c4f55fb0ae090613186d3327"
                "44e9b905ed808eacbff220909fa809b83976e6137ed99af7cbdaa8bb16274463d7087a2c"
                "84f4706b89354db8a29ce7275d6afa50a4ce632476ec36a1ce90b61a32278956a1b16c28"
                "c94ceb02413412533fe33a397087635b584039e86819e487482f1a6b6bdf003367bd1ab5"
                "765109701d8569efc5257fa91aa37ade1e19f449616923bb4bed20c236145a94589aaa99"
                "9a37ac36f7b0822ecf439d5c99a3a5f1a4f12b090546bea1c8c192eb66af25e2d4c5c2c6"
                "3d510003fa836e7e2939b513b9278aa5aeaa5341e973bc01ac5bbda1567f82c3f44f8fa9"
                "84798c817bd0bc0e202759c4aaca058af8867a8bc2b076724970663789d9d1fa6e55d0aa"
                "700884ae54929a155ff07cd293aaf595765b66127db2e5c65129b48aad3805fd8c8d7c70"
                "ea0714d6eda049a669bbc1a407e97b94fd074b0deaa823e4908aae9c23b36a85049fba98"
                "fa3ac65388e53f386b28a864b9d68a324b9e85fdf4c8ee9d1bb93436bb5d17a12c7d176a"
                "52140e4d9618d851d178b4a6ed317721643cf9844b261274b4fd6ef2911fb30f7286357d"
                "14811a2afaa241847c2e888ef8259883afe58726b36e6974c2fa022580245c859e8b36ef"
                "295acab45ad6cb05ab220081340fdf4be2fb2826e323b85dfb587fe81f756e7ce00ea5ea"
                "4f8a8804e518f30bc46e321799cab9a46c69be594a95e69c664c22ab4e7441c240dd6dbb"
                "58de55279db182007823746eff95bd0bb81f527199d81881036dcb5f8680a8648add66cc"
                "9c7371855845aa8514c2a1358bccb97b1c501a9585c248f25d9d58b4dd817a611541d51c"
                "fadde7f515c42b792ca1a931947ad5244f1422983758e66255378e9965b5ea87a980a198"
                "60aff925f5cd19898eadb0f6bf215f20ea1862c2ca5c54af54395903f2d5373874a0b4be"
                "86dd8224749b341d55019c027797d61e18c5305a235620523a51136181f437a4a68b5091"
                "07aa96571347592b9d6e1db35fc0db9334a1831269d9556cec52f6d7383238dc0524c2e4"
                "51f495796e2541743c011b0aeb7d4364d5689646ec4a1650b408107d47eec153900a9b92"
                "40d3a12c17f36eb88a123b5bbd0451e9f0072676a6ca10028f881752760ab496e3c26e66"
                "c478a6134b1ce80ff1e429a17a56c7fb171d7c92719f90281760875dc6d81ae6d191c02d"
                "f9ab27987d168692d243d7bad59c28a51a465541744b26c0511062459a9d42756ea1c773"
                "3720e394245d82fca28545d6da64482abbb061bde5b48954b33c22ca551361459e454875"
                "a43c03a2f89962e97fade6d4a929e2c807ca2631c6c0c5a87938e38d9056b10e9c51a560"
                "d14899f5ba0c50fab3b28be1cd5dd4305cb895224899aa09e6a54e58dc"
            ),
            message=(
                "225d5ce2ceac61930a07503fb59f7c2f936a3e075481da3ca299a80f8c5df9223a073e7b"
                "90e02ebf98ca2227eba38c1ab2568209e46dba961869c6f83983b17dcd49"
            ),
            signature=(
                "3a08e25538484cd7f1613248fe6c9f6b4ec14be684c6defdd1e41333b6e9052ac4340e31"
                "4eea2c99f7bb38dc6185aff2e37b8bdac450d5a6b92eb3ee618d4601a0cf9e78ac0f31d2"
                "3edc6b7eb202bba65fad462f2f1a692e7dcaae7937a9c271b83316a63e15f485d48217b8"
                "fa98905d553e8cde2f8472585f8a713a272c1c99ff5cac93d85abddc7cb1f0afbe1eb8c3"
                "9a733685335105ebe7a4e136d866cbbc923c52ac22cd52b6be9883d3b0c599964da3de30"
                "e9398e9e41cfaa6d62a333e4baccb0daa45a8f8d1e5974c43bb28ce5a8ae515fc43aeb8b"
                "2125e1f46dad35fad8c92dff1a868a709cf3ef971e1fcda0eb5cd2844380a3f4a4cdb914"
                "6ddb3edc1afb403718b4b1e2ce9735d36734f6d4a0655d064ca90a8330c2a1085ac50b9a"
                "0895d34b817d62e5353bde1c7714477ef1d55f890db351bada3b3d4d7682cc3ba933895a"
                "cf4dc34ab335ae74ba8b16815315acb3f0c424886ed386b111f8c52d0fc8635774a53341"
                "497230ab5f30694aa3784a39325967538694f927ca14672285b0e9229bb759e219530c24"
                "504487b5e1db9c3cf09d3aed3cfe729a8ea48b3f55ab23452f233c89a1c8fd1a670e7a59"
                "3ac4cb6658b4d47aa20fa87bf7bd9dde43e546ed3a7897c61b6c0cdf69b430d92dd5daff"
                "c2c210cbb2b76fe641e2eab67fd38cbdc0e3dce4052d742b4eae565daa76eab63e0bc925"
                "c546581cd2f8dbdab9938a1df6718d984e7c9c072ba1e6facb14681bc16b5fb6b1e80091"
                "69709cfc3c0996a8e53a08836ef9e1d7196a3ae84cbcdbead2653c45af360b32bb3dfe66"
                "5bcc7238615d54aaeace222f56eb42b4c9cb3262a89dd308e5630eba7f05f1c2d34681b2"
                "f6686d994b6db1cdda8bc3cda3313b7c18c7c1d44408edf57fac6237e546b7abaeba4a60"
                "e56b3f63b51fdf29ce712c2626c1c7c20ca36bb35736cede41544ef13c47fc814cb8db96"
                "1390808a7c292477222b19e54c56876b7a9877e46c4a0048d4bf64c113244c6205c983b9"
                "65e1f797fe2d4deb9d944932d81de325d4b5a80cd4992a4f3c47e1c54821db7b42990b1b"
                "25850c462c5263496642c6997f728d104313f8ab67817bac7b0f57536c5e5aa94efa9edb"
                "ebb17c3704b160c9c9ed960a529541b9d3283d1f9cd56b884752a66d93bd22f45e0073e9"
                "a8a49aae485b4c9b69ae30b9329befb020d3fd38d4298769b0a020394417cb2058652f89"
                "45f4cbf0638f21719b2cbd7d8b575c9f9a299c8d39cddce644bd4ba0adb254458c9b8d12"
                "ec2431d86b51cd9cfe15f92b295c635abbe50b9534dbc8e2f6e36f4b94aeeec4ddc1aef4"
                "9c498575dc3ec465a1e73752f41e008dddb39457654e6a77c873ebcd4fe08401bb8191ed"
                "ac5264232eab26661c69a74ff702971385df0e84d818caa6cc86b984058e81926fdc5510"
                "4e5bc85ce379b583e5b7e5d9cccdb5dd1531b5688f82b2aef60a62473a65da9bf73b02de"
                "a70f0fe9eeabd10fe46368e925232ddc8bb1cebceaddc020e4964c5ecc9980425bae656e"
                "94e41fe2f19223d8b80aa395f263cea33c8d2a3de5d1da71cc1766a243478a11d76c3577"
                "f4ddd193d839748f4da9d06a372acf5c68939ffe93c1b01bac82409ee21bac24329a968d"
                "b2e9844c33cd09dee38edb1dbf8af8d71a0defbc8d4c5c1362c5b50d492d4aadb2366ac3"
                "31af477151cc870b682c18f4f7b499f6e9d8cf4a230069e06d9c512bd64bb9eed28dafb6"
                "100c08443710e489aa32cf0b09afc32f6f7f418042367c251287cc5192b94d3cd0da4cdc"
                "def4b5f7d1c53509efe4dd740000000000000000"
            ),
        ),
    ),
}


# The `sk` field of the same two records, which `VECTORS` deliberately does not
# carry. Adding `secret_key` to a `Vector` would make `kat.check`'s signing pass
# reach `Falcon.sign`, and that is #27's `NotImplementedError` — so the bytes
# live beside the records rather than in them, and drive §3.11.5's decoder
# directly.
#
# What they gate is worth naming, because it is more than a round trip: the
# reference implementation's own `f`, `g` and `F` are here, so a decode that
# recovers `G` by (3.35) can be held to `f·G - g·F = q` in exact integers, and
# the `h = g/f mod q` it implies can be held to the **published public key
# above**. Two implementations, one key, three independent agreements.
SECRET_KEYS: dict[str, str] = {
    "Falcon-512": (
        "59044102f3cfbe1be03c144102f7ef75fbef83043f7cfc20c20beec007de3f041fbf0bff"
        "401041030c40040fae7e103f7e100085fc013d1410c80c2f000810461c2f480bee8017d1"
        "7f07f1411ba24013c1bdf83dc407d17e07c13917f0f9044045fc40bd0ff07d07ef0003df"
        "c1f3cffd1fc03fefc0b8fc6e7b0bbdbd0fe0be17d14307effe0fbfc6f81fbff43ec1f870"
        "41d42083ec3dc2f4407bf84ec4140fc403f037f3fec013e0fee02180082f83fbe07bffe0"
        "43f40ec6ffb1bf200007ffbffa0fff6ffbce83ebfebefc0ffdf3f103fc6f3ff0500a1871"
        "8308007d03f200e4213bf04ffd17d000f0017a17f180e04fff07dec2244048148e870450"
        "3ee06f86080243f81fff03bf4003f07ef3de02fbffc00420c1f40fbdf0707e043ff5ffd0"
        "000430400c4f49f4207c142f80ec3e010bff7c13f07ff85f7f17e07c17ff33fc4ec303ff"
        "bcffeec41830ff0831bdf45f05f06fc503b0c0f84e4013e100e7e1441450c2fbeebc0c0f"
        "befc60bcffef3cfbdf4303ef800bf2be0bf001f01f43f41ffe08517b001141e00144f7ef"
        "8007cebdffff4213a0b9f8a0fe04103c17e0820bb1c30c30c00ffffc00007d18017cff90"
        "c3101e7e103040fc4fbe04213e07af80ffefc80fbfbd0810bcfb8fbc087fb8fff1010c2e"
        "81002f3ef3bf01f07e41fbc07f2c0fb8f43f401c5d81ffcebe07c07e0bf17eebee830c51"
        "4003ff7ef3e08403d1ffffe105f840c20bdf0607fffef46e7efff08000400de830000f3f"
        "82ef9d82e84efff3cec4e81e01002103102efc080f3b0801041bae42f7f040f83ec31010"
        "031bc0410faff9f0004010133a089ffef7be8317a0020fef010052ba04107e100f821c2f"
        "41f44f4ef7b000f02e41f82f380830fe08a1f707ff82ec7f42e81004041103e8307b13d0"
        "fdff8f830f9fc5ffcd7e040f410fffb9f423750860c11c5ffa144ec0080f02dc0f420820"
        "450790020bcf80efffbcec4fbff4200afc00c02060c004303ef81ffa104107e4117af01f"
        "81202fc1e44143ffe206eb3e881bb13f13920403ff7a000144102e7ffc2143e7ff4af3f1"
        "3f07e181dc317e240f4500303f2dddcf1e1513e3ef15e8dc1309e50aee03efdc17081706"
        "fd03e6ece4f30ebd1909051906e90ce806eb0b19e719effbf10d0df1dc0cf6f1f4f8fefb"
        "e9f9550e2107fcdccbdfe9f4f7ee1af8142115f910002af2f5ff141ada220aecfe040cef"
        "0b29eb201930f2d3e401e5deeff4ddea17f1fe141217f81c36050109f8f61f02dd19f903"
        "10c7f40208e9052c3942f8fff2ccf9fdf83cfa12dc091c0d02f00411f5281e40d7f92dba"
        "11d73d04c10bfd13e617110af3ed05f6cfe705e0f70e1ff80533fc120c002ce81ff52638"
        "190fe3fed6f0fbbb23e6f408ef32220b13dd27f007e5fa00d72614f0e302210707ec111e"
        "070e2a032df91de3fce800f1f9f2f7fe170101180412cbd1e90019f2011522daeaed13f8"
        "e5f425dcef24e01ce614e7dcec01f2f4f914f4010107ed26e2e9df0bf5f007ea07fafbc6"
        "d7e607fafcfd270dfd0d17fc4ef0ee00071aecde09f8f215e113f80209ccf308d7e6251e"
        "ce0edfed0cc9f4050b2714f61bf703f0ebf104010debfbf21afc1bf01823fedefaf7f807"
        "e3f3020aeb01fe19eee8e90d00e5faed1efdf628e5f0e6f0fc13f4fb05fb0b09ea0a0e08"
        "ee13293212e90ce4fef223f4ff030bebed1b402ed2f6171102bc0cf9e9f335ed0c01faf0"
        "fefae41df0050a162c11171cd90bee211218edfafa0f03f4171412f319d60b01faee1f28"
        "23f0d6ef12d6dfeafbfc170decda06e7ced500031e"
    ),
    "Falcon-1024": (
        "5af9060e0b80f0cdee037f0842208ba4173de07c3fe701918bfdff49df0003e7ca31185e"
        "00402d7c7f07065e838427fdf173c5ea0a0f13c2e787f1ec401f7c3e8ffa00c2106c3ef7"
        "80606be0067a1f0fdd078440843cf0b9f28045ef88108002e7fe2e7fc2ff3e0e001f1943"
        "ce80a310402117e0f77e110bfff8c4217c44f0c4307c21183bb084a4103fe0747c0f8002"
        "707bf8065f03fed7821dffa0f7822103a2c7fc51770217f80f0f5f174411709bf7822fff"
        "60270203f81d19bff07c42f981e07c3b30c7f008200f79f1147f37c41e780300bbe1ff9e"
        "10be00680029800ff7e026f83200031ff60fff5f18c3df0804d849ff0401f0021f7c6517"
        "3bb1f7b920b9bf0402efb7d0efc208441fffe3f83e0003fef7ffd0033f1781e1081f1002"
        "3f705c1fff93841d28f432806220fba0fc60f8c60e87051842200c621841c0081e277bfc"
        "f3fc263e0ef87ee8405e745e2048620420f73c207820183bce883f07fdc0fc9fffc1a37c"
        "87103e1ef81c08080f67e0ff0a1f0482f6c3e093dc18422f877de7881d0bfef8bdd28bfc"
        "28400070440ec9e103c0d7c1f1ffdf08b78df48008bc120063ff8420fc1b08c61f0fa201"
        "c040084008824effdff7c03f9000f845dd7be30ef82fe83f1001de8421303e0efc61e0ff"
        "b004211fffcf7c40eec21ff858f83e0087a4ff41e08c3ae80001e43d2141e20404c803a1"
        "07ff00bc4f0404efc05f84ffdf87f17406177c307060013c307c9ef7be5f0021f8bfd214"
        "201f83f0f81c0fc9c2901bf0fdff807e27fe0d8ba117f82f849fefffef841efe80107c02"
        "e08022003f1fbfd29c7b083a1117c0ffffe193a210cbb190002081cf801f187bdd7441e8"
        "3a00781f200a00707fd00210807afffc3ff87ee8744380000e420d8c7e10bbc1783f0043"
        "e0f81e21be0f8081e80df104dd188a00043ee80012034508441f0bbdf84000ffff07ca10"
        "f3bdf0bbe284220843fe0042074dcf83e3f0ffb30bc216403f8403ff8621031f08444194"
        "20e8c6118c00eff990f85b07400178600ffe00fc02eec7f0041d08fc516821f088527c81"
        "0a3602903f17c7f46eff080e0ff89d204641740017805ff462f08200f000003fef87c200"
        "3ddf7c3d0878417c220f41c060850788410bfc08b7a107c40887e0902117c4137be3ef00"
        "0f93e3e7fe3083bd2087f08901ff8260fc43110df383c0000270ff42e943cf8443f8b61f"
        "17e30f45e0fb20f005eef3bfe78a600bfe3141ef7c00df400cfbc10e87f288bfe10a130b"
        "dee9043f80010800008806e78fd00bfff843fff3ff08082f879ff740617c6101c5b1043f"
        "07bc108bc3f94a0ff7a53079e4843f178c1088250f428f789f3f863f8000183a00787df9"
        "3bd08380280403902217f430845d1740110b25f8361e83c1193e3f0c7ee10010707ef806"
        "0f8fc111000efc3e0845df8fe0183c1ff79d0981dff83e083fff6c81e8fdb0000210386f"
        "9be3004800901bd7c4100fa300c4200cbe27b5e2efe3f94010003ff885f0f7a2e8c3f088"
        "20d8bdd08061f6843280a107fc316b5feff830f3e20ffbff83c228b41e77a1fec5ff7ce1"
        "efc00f843c070651e7fef8f8307c030004328fa4000bf083e0e70442679d20c5a0f841f8"
        "3c41847fd7c631f88120020f8021f74420fc3cee840f10da10fbd27461f8000d03c2f08d"
        "ef081ef83e810440084240fbc017842e80e2217dff987ff0fe001bfdf0323f04c10839c0"
        "807e108041f840f7fa0117bb07f87f905ff085e1fffe200a1008410841e2103b277fee90"
        "3bfeb9d16743d0fffe84fe2881f1f85a078df1fffd070befe402ff1c03fc0513ecfde419"
        "0ffed5150906dd06d4eeded8ec0ac8f6e4180de308d813fe2401fc1427ea0605ea2c08e8"
        "05c8cf1319fc07c8e909fbf609f006ff0b190e0cfb0cf3051707e7fdfe2b1200fe1c0cf7"
        "0ad42412defdf6024627ec04f61d1be81cfa32ffe1ea0f24ef06f9f422f2fc06f213f7ec"
        "2aea03ff140d0d17ee023e072808c7130cf5cf05370b30d2ee02dc1c41eec0e0fbfe111f"
        "f4c21cf4d1fb0bdc2bfd1e1315d301c014e5120608240e0f06e132cbe533d200001b032d"
        "c322fc11d1f4d81909110404f9100ef30eeb23ec20e90ff9dad81425f0d6ffee16f12818"
        "3aed0daa10e7ed0e2514f0ddfac81c16e505fdf6df231a190309e925f504f1eb02d7e9e7"
        "1f22fc03ec1627fabd030d24fb21fde7f41ad007f743f2f61b21092300e1fe13fbcb06e3"
        "e30e0210f10aeb1ef010e62332eafc11f5c804f4fc151aed1fe9fdea1c080a042df1b9de"
        "0af116ff01ed19d0ddfcfd021b251e0924efe30814c8e8f6f7ddd0e7ed2e1006e5f00404"
        "f9150119ffe817f1c0e9de101308d4ffffdcf50ee3f1fbeef4f9111c27e20a1ddfde09e3"
        "3fe7dc1d33f700eafcf4f606110c19fc360801f62f16ef11e41e162022071df0120afbfe"
        "0f46fcf11d25e3201ef30be8ebef10d4eb19181feee4d400e3280a1fcfdbfcef18f3f709"
        "ea04d4f9fe041a0afa0bf8d5e1cc0b13141af5f3f016f2fb2000f6f0f2070fc5ecfacdf7"
        "ebedf1e9e81d17fb2bfc0eecdbee0e060ff710fbe4e6da28261cf3f1031a180a160d0123"
        "f5febe15ef33f918eb07ffe115231eccec1f0a083913f8f413f60df0e1f1fcf713ff1ee2"
        "18fb081b1a0707ea09fb08141fc5fa1223fbe7f6d61cfc2d24f0f0dd27eede141c10fff7"
        "fd48e3ee1611e4f7dc252ff7fd11ccfbeffee9ffca03f0f108f3f10d04d01fdc12051ddf"
        "d61ccbdfffefe3f43123ebd3ff024300e2cf0c06e1123a1906db20040f2fe830f5ed0e41"
        "f4022efbe222f1fbcc211414e502e411c7eb193804e7d811ce1e0ef70116f1f2eb5f03ed"
        "fc030d28061e1605e4f0f9f61ef5ecf4f414e70c0a22f6bdf62e190307fc0ffb14101ff3"
        "050c45ebc40408f6f517110210c51700f9dde3190cf8ee1eca1ce3dc3ee816fb01250c01"
        "eb12fe01f3e917ff0907cbd00c031227db1fd3de0419fd291305c0f20f0f0ff5f4eef72c"
        "ef15e7d4d71c3bcd0dee05ff0bd02ed2e3e125f7f3ff1de4ede92beeea1304e3fdfe05ce"
        "d9f6fd1cf816ee2ae314f30f0420e51421ebdcf6f1e7072bf739e30c19db003426f5e7e1"
        "e10417f6ddf70df5f10d09fb2d2be821191f0cf8f831fe0b2004eef82e4720fc04fced0c"
        "eb1829d0f014f808ead72df5e942131719c1f1e5e5eafd1be7d41bd2dae8ecfe12d82f08"
        "d4140f1510fec900ecc80017e921ba07e9ef0a15f40ccad2ed171926c3f912ed0a0c05f1"
        "11"
    ),
}


PUBLIC_KEYS: dict[str, str] = {
    name: cases[0].public_key for name, cases in VECTORS.items()
}
"""The public half of the record each `SECRET_KEYS` entry is the secret half of.

Derived rather than transcribed — it is already on the `Vector` — but named
here so the two halves of one published pair are reached the same way. A test
signing with `SECRET_KEYS[name]` and checking against `PUBLIC_KEYS[name]` is
making a claim about that pair; spelling the public half as `VECTORS[name][0]`
at the call site makes the same claim look like a lookup.
"""


def vectors(name: str) -> list[kat.KatVector]:
    """One parameter set's cases as the shared harness's record.

    `valid=True` throughout: every case here is one the reference implementation
    accepts, which is what the harness's derived passes need as their starting
    point — a moved bit is evidence only against something that verified before
    it moved.
    """
    return [
        kat.KatVector(
            case_id=f"falcon-round3 KAT {name} count={vector.case}",
            parameter_set=name,
            public_key=bytes.fromhex(vector.public_key),
            message=bytes.fromhex(vector.message),
            signature=bytes.fromhex(vector.signature),
        )
        for vector in VECTORS[name]
    ]
