# Copyright 2026 The sig-frx Authors. SPDX-License-Identifier: Apache-2.0
"""Falcon known-answer vectors, loaded from the round-3 submission package.

Falcon publishes no ACVP set, so the authority is the one
[`testing.md`](../../../../docs/reference/testing.md) names next: the reference
implementation the standard points at, and the vectors its own generator
publishes. These are those, read from the archive rather than transcribed.

## Provenance

- **Upstream:** `https://falcon-sign.info/falcon-round3.zip`, sha256
  `d625407dbda9e5835f610aaeba1147e029988a6610e0107dfd292033138e1d47`, pinned in
  [`MODULE.bazel`](../../../../MODULE.bazel) as `falcon_round3`. The round-3
  submission is frozen by the NIST process, which is what stands in for a
  commit pin.
- **Fixture:** `KAT/falcon{512,1024}-KAT.rsp`, generated by
  `KAT/generator/PQCgenKAT_sign.c` against the submitted reference code — 100
  records per degree.

**FIPS 206 is still a draft**, so its vectors do not exist to prefer: NIST's
`usnistgov/ACVP-Server` carries `gen-val/json-files` directories for
`ML-DSA-*-FIPS204` and `SLH-DSA-*-FIPS205` and none for FN-DSA. When it grows
one, that set is the authority and this file changes source; the check is a
directory listing, not a judgement.

## `sm` is §3.11.6's aggregate, and the seam takes §3.11.3's signature

The NIST API packs a signed message as `siglen(2) ‖ r(40) ‖ M ‖ header(1) ‖
enc_s`, with a **nonce-less** header of `0010nnnn` — the salt already appeared
ahead of the message. The seam takes what §3.11.3 defines instead: `header(1) ‖
r(40) ‖ enc_s`, header `0011nnnn`, zero-padded to `sbytelen`. So each record's
signature is that regrouping of `sm`, which
[`falcon_reference.signature_from_aggregate`](falcon_reference.py) performs and
asserts its way through — the same transform `falcon_oracle` runs to hand the
reference's own output to the seam, held in one place so the two cannot drift.

Regrouping bytes is not the same as inventing them: every byte is upstream's,
and which field each lands in is what the two sections state. The padding is
the only thing added, and Algorithm 18's trailing-zero rule is what makes it
unambiguous.

**One published record has no §3.11.3 encoding, and it is dropped rather than
coerced.** The NIST API's signature is variable-length and the KAT generator
drives the raw signing call, which has no equivalent of Algorithm 10's restart
on an over-long compression — so a record can exceed what the fixed-width form
holds. Exactly one of the 200 does. [`unencodable`](#unencodable) reports which,
and [`falcon_kat_test`](falcon_kat_test.py) pins the answer — the boundary is
data, so the loader states it and a test asserts it.

## What the records carry, and the two things they deliberately do not

A record carries the public key, the message and the signature — the three
inputs verification takes. Both secrets are withheld from the record itself,
each for its own reason, and neither is an oversight:

- **`sk` is exposed separately** as [`secret_key`](#secret_key) rather than on
  the record, because [`kat.check`](../../../testing/kat.py)'s `_check_sign`
  drives any vector carrying one into `Falcon.sign` — still
  `NotImplementedError` until [#27](https://github.com/fractalyze/sig-frx/issues/27)
  lands its signing loop. §3.11.5's decoder is gated on those bytes today by
  [`keygen_test`](keygen_test.py), which is what they are for.
- **`seed` is not exposed at all.** `_check_keygen` would take it and require
  `keygen(seed)` to reproduce the published pair, and this repo's expansion is
  `SHAKE256(seed ‖ attempt)` rather than the NIST harness's AES-256-CTR-DRBG —
  a decision recorded on [#26](https://github.com/fractalyze/sig-frx/issues/26).
  Reproducing these keys would mean transcribing that DRBG and the reference's
  own sampler and restart order, none of which is Falcon's specification.

So **key generation and signing are not covered by this set**, and that is a
property of what the generator published against what this repo chose to be,
not a gap to be closed later by loading more of the same file.

## Volume is bounded for the per-PR gate, and unbounded for the sweep

The generator gives record `i` a message of `33·(i+1)` bytes, so a published
set is 100 distinct message lengths per degree and nothing repeats. A traced
`hash_to_point` compiles per distinct shape, which is exactly the cost
`testing.md` describes for ML-DSA's set — so [`vectors`](#vectors) takes a
bound and the per-PR gate passes a small one, while
[`falcon_sweep_test`](falcon_sweep_test.py) passes none and runs behind
`slow_kat`. The bound takes the *shortest* messages, which is the cheapest
subset rather than an arbitrary one.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import NamedTuple

from python.runfiles import Runfiles

from sig_frx.lattice.falcon.testing import falcon_reference
from sig_frx.testing import kat

_RUNFILES = Runfiles.Create()

_PATH = "falcon_round3/KAT/falcon{}-KAT.rsp"


class Record(NamedTuple):
    """One `.rsp` record, as the bytes its fields decode to."""

    case: int
    message: bytes
    public_key: bytes
    secret_key: bytes
    signature: bytes


def _parse(text: str) -> list[dict[str, str]]:
    """The `.rsp` file as one dict per `count = N` block.

    The format is `key = value` lines in blocks separated by blank lines, with a
    `# Falcon-512` banner first. Parsing it as blocks rather than by regex per
    field is what makes a truncated record an error here instead of a silently
    short set downstream.
    """
    blocks: list[dict[str, str]] = []
    current: dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            if current:
                blocks.append(current)
                current = {}
            continue
        key, _, value = line.partition(" = ")
        current[key] = value
    if current:
        blocks.append(current)
    return blocks


@lru_cache(maxsize=None)
def _load(name: str) -> tuple[tuple[Record, ...], tuple[int, ...]]:
    """`(expressible, unencodable)` — the split, and nothing decided about it.

    The boundary is reported rather than adjudicated here, which is what
    `ml_dsa_vectors.excluded_by_reason` does for the census its own gate pins.
    A loader that raised on an unexpected boundary would fail every consumer,
    including two benches, where the claim belongs to one test.
    """
    path = _RUNFILES.Rlocation(_PATH.format(falcon_reference.PARAMETER_SETS[name]["n"]))
    if path is None:  # pragma: no cover - a packaging error, not a case
        raise FileNotFoundError(
            f"the {name} known-answer file is missing from the runfiles; "
            "the test target needs `@falcon_round3//:kat_vectors` in `data`"
        )
    blocks = _parse(Path(path).read_text(encoding="ascii"))
    if not blocks:
        raise ValueError(f"{name}: the known-answer file parsed to no records")

    out = []
    dropped = []
    for block in blocks:
        message = bytes.fromhex(block["msg"])
        case = int(block["count"])
        if len(message) != int(block["mlen"]):
            raise ValueError(f"{name}: `msg` and `mlen` disagree at {case}")
        signature = falcon_reference.signature_from_aggregate(
            bytes.fromhex(block["sm"]), message, name
        )
        if signature is None:
            dropped.append(case)
            continue
        out.append(
            Record(
                case=case,
                message=message,
                public_key=bytes.fromhex(block["pk"]),
                secret_key=bytes.fromhex(block["sk"]),
                signature=signature,
            )
        )
    return tuple(out), tuple(dropped)


def records(name: str) -> tuple[Record, ...]:
    """Every published record at one parameter set that §3.11.3 can express."""
    return _load(name)[0]


def unencodable(name: str) -> tuple[int, ...]:
    """The `count`s §3.11.3 cannot express, which `falcon_kat_test` pins.

    The NIST API's signature is variable-length and the generator drives the raw
    signing call, which carries no equivalent of Algorithm 10's restart when
    `enc_s` compresses longer than `sbytelen - 41`. So a published record can
    exceed what the fixed-width form holds, and one of the 200 does.
    """
    return _load(name)[1]


def secret_key(name: str) -> bytes:
    """The count-0 record's `sk` — §3.11.5's decoder gated on published bytes.

    A `Record` carries this and a `kat.KatVector` does not: [`vectors`](#vectors)
    is what withholds it, because the harness drives any vector carrying one into
    a `sign` that does not exist yet.
    """
    return records(name)[0].secret_key


def vectors(name: str, limit: int | None) -> list[kat.KatVector]:
    """One parameter set's cases as the shared harness's record.

    `limit` keeps the first `limit` records, which are the shortest messages
    because the generator grows `mlen` with `count`. `None` is every record —
    what the sweep takes.

    It has no default on purpose. Every caller states the volume it is paying
    for, so a bound is a decision in the reading rather than one inherited from
    here — `testing.md`'s point that a gate which quietly stopped exercising
    something reads exactly like one that got cheaper.

    `valid=True` throughout: every case here is one the reference implementation
    accepts, which is what the harness's derived passes need as their starting
    point — a moved bit is evidence only against something that verified before
    it moved.
    """
    # `seq[:None]` is the whole sequence, so `None` needs no branch.
    chosen = records(name)[:limit]
    return [
        kat.KatVector(
            case_id=f"falcon-round3 KAT {name} count={record.case}",
            parameter_set=name,
            public_key=record.public_key,
            message=record.message,
            signature=record.signature,
        )
        for record in chosen
    ]
