# Copyright 2026 The sig-frx Authors. SPDX-License-Identifier: Apache-2.0
"""The SLH-DSA address structure — FIPS 205 §4.2, encoded per §11.

Every hash in SLH-DSA is tweaked by an address saying exactly where in the
hypertree it sits: which layer, which tree, which node. That tweak is what stops
a hash computed in one position from being replayed in another, and it is the
most error-prone part of the scheme — a field packed in the wrong order produces
an implementation that is perfectly self-consistent and fails every known-answer
test with no signal about why.

An address is structural, never data-dependent: it is a function of where the
caller is in the tree, so it is built on the host and encoded into bytes before
any hashing starts. `encode` and `encode_batch` are that boundary — everything
above them is Python integers, everything below is a `uint8` array.

Two encodings, and a parameter set uses exactly one. The full 32-byte form (§4.2)
is what the SHAKE sets tweak with; the SHA-2 sets use the compressed 22-byte
ADRS^c, which §11.2 defines as
`ADRS_c = ADRS[3] ‖ ADRS[8:16] ‖ ADRS[19] ‖ ADRS[20:32]` — the same address with
the leading bytes of the layer address, tree address and type dropped, all of
which are zero for every address a defined parameter set can produce.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass

import numpy as np

# Word sizes of the full encoding, in bytes (FIPS 205 §4.2, Figure 1).
_LAYER_BYTES = 4
_TREE_BYTES = 12
_TYPE_BYTES = 4
_WORD_BYTES = 4
ADRS_SIZE = _LAYER_BYTES + _TREE_BYTES + _TYPE_BYTES + 3 * _WORD_BYTES

# The compressed encoding (§11.2.1) keeps only the low byte of the layer address
# and the low 8 bytes of the tree address; the trailing three words are unchanged.
_COMPRESSED_LAYER_BYTES = 1
_COMPRESSED_TREE_BYTES = 8
_COMPRESSED_TYPE_BYTES = 1
COMPRESSED_ADRS_SIZE = (
    _COMPRESSED_LAYER_BYTES
    + _COMPRESSED_TREE_BYTES
    + _COMPRESSED_TYPE_BYTES
    + 3 * _WORD_BYTES
)


class AdrsType(enum.IntEnum):
    """The seven address types — FIPS 205 §4.2, Table 1."""

    WOTS_HASH = 0
    WOTS_PK = 1
    TREE = 2
    FORS_TREE = 3
    FORS_ROOTS = 4
    WOTS_PRF = 5
    FORS_PRF = 6


@dataclass(frozen=True)
class Adrs:
    """One address.

    The three trailing words carry different meanings per type — key pair
    address, chain address or tree height, hash address or tree index — and a
    type zeroes the ones it does not use. They are stored as one tuple rather
    than as named fields precisely because the names are not shared: `TREE`'s
    first trailing word is padding while `FORS_TREE`'s is a key pair address, and
    a field named for one of those would be a lie in the other. Build through the
    per-type constructors below, which name their arguments the way Table 1 does.
    """

    layer: int
    tree: int
    type: AdrsType
    trailing: tuple[int, int, int]


def wots_hash(
    layer: int, tree: int, key_pair: int, chain: int, hash_index: int
) -> Adrs:
    """A WOTS+ chain step."""
    return Adrs(layer, tree, AdrsType.WOTS_HASH, (key_pair, chain, hash_index))


def wots_pk(layer: int, tree: int, key_pair: int) -> Adrs:
    """The compression of one WOTS+ public key."""
    return Adrs(layer, tree, AdrsType.WOTS_PK, (key_pair, 0, 0))


def hash_tree(layer: int, tree: int, height: int, index: int) -> Adrs:
    """An XMSS tree node. The first trailing word is padding, not a key pair."""
    return Adrs(layer, tree, AdrsType.TREE, (0, height, index))


def fors_tree(layer: int, tree: int, key_pair: int, height: int, index: int) -> Adrs:
    """A FORS tree node."""
    return Adrs(layer, tree, AdrsType.FORS_TREE, (key_pair, height, index))


def fors_roots(layer: int, tree: int, key_pair: int) -> Adrs:
    """The compression of all FORS roots."""
    return Adrs(layer, tree, AdrsType.FORS_ROOTS, (key_pair, 0, 0))


def wots_prf(layer: int, tree: int, key_pair: int, chain: int) -> Adrs:
    """A WOTS+ secret-key element, generated by the PRF."""
    return Adrs(layer, tree, AdrsType.WOTS_PRF, (key_pair, chain, 0))


def fors_prf(layer: int, tree: int, key_pair: int, index: int) -> Adrs:
    """A FORS secret-key element, generated by the PRF."""
    return Adrs(layer, tree, AdrsType.FORS_PRF, (key_pair, 0, index))


def _to_byte(value: int, length: int) -> bytes:
    """`toByte(x, n)` — FIPS 205 §4.1: the big-endian n-byte encoding of x."""
    if value < 0:
        raise ValueError(f"address fields are unsigned, got {value}")
    try:
        return value.to_bytes(length, "big")
    except OverflowError as exc:
        raise ValueError(f"{value} does not fit in {length} bytes") from exc


def encode(adrs: Adrs, *, compressed: bool) -> bytes:
    """The address as bytes — 22 when `compressed`, 32 otherwise.

    §11.2.1 defines the compressed form by taking the least significant byte of
    the layer address and the least significant 8 bytes of the tree address. A
    field too wide for its compressed slot raises here rather than being cut
    down: no parameter set the standard defines can reach one (the tallest
    hypertree has 12 layers and 64 bits of tree address), so an overflow is a
    caller that computed the wrong address, and silently dropping its high bytes
    would tweak two different positions identically.
    """
    layer_bytes = _COMPRESSED_LAYER_BYTES if compressed else _LAYER_BYTES
    tree_bytes = _COMPRESSED_TREE_BYTES if compressed else _TREE_BYTES
    type_bytes = _COMPRESSED_TYPE_BYTES if compressed else _TYPE_BYTES
    return b"".join(
        (
            _to_byte(adrs.layer, layer_bytes),
            _to_byte(adrs.tree, tree_bytes),
            _to_byte(int(adrs.type), type_bytes),
            *(_to_byte(word, _WORD_BYTES) for word in adrs.trailing),
        )
    )


def encode_batch(addresses: list[Adrs], *, compressed: bool) -> np.ndarray:
    """A batch of addresses as uint8 `[len(addresses), size]`.

    The batch axis is where a caller hashes many positions at once — a WOTS+
    chain, a Merkle level — and the addresses vary per entry while the seed does
    not. Building them here keeps that loop on the host, where it belongs: an
    address is structural, so nothing about it depends on a traced value.
    """
    if not addresses:
        raise ValueError("no addresses: an empty batch hashes nothing")
    encoded = [encode(adrs, compressed=compressed) for adrs in addresses]
    return np.frombuffer(b"".join(encoded), dtype=np.uint8).reshape(
        len(encoded), len(encoded[0])
    )
