load("@rules_python//python:defs.bzl", "py_test")
load("@sig_frx_pip//:requirements.bzl", "requirement")
load("//:defs.bzl", "GPU_PLUGIN_DEPS")

py_test(
    name = "frost_test",
    size = "medium",
    srcs = ["frost_test.py"],
    data = [
        "@frost_ed25519_sha512_vectors//file",
        "@frost_secp256k1_sha256_vectors//file",
    ],
    deps = [
        "//sig_frx/classical/eddsa:ed25519",
        "//sig_frx/threshold:ed25519_sha512",
        "//sig_frx/threshold:frost",
        "//sig_frx/threshold:secp256k1_sha256",
        "@rules_python//python/runfiles",
        requirement("absl_py"),
        requirement("numpy"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "xmd_test",
    size = "small",
    srcs = ["xmd_test.py"],
    deps = [
        "//sig_frx/threshold:xmd",
        requirement("absl_py"),
    ],
)
