load("@rules_python//python:defs.bzl", "py_test")
load("@sig_frx_pip//:requirements.bzl", "requirement")
load("//:defs.bzl", "GPU_PLUGIN_DEPS")

py_test(
    name = "adrs_test",
    size = "small",
    srcs = ["adrs_test.py"],
    deps = [
        "//sig_frx/hashbased:adrs",
        requirement("absl_py"),
    ],
)

py_test(
    name = "tweakable_test",
    size = "small",
    srcs = ["tweakable_test.py"],
    deps = [
        "//sig_frx/hashbased:adrs",
        "//sig_frx/hashbased:tweakable",
        "@hash_frx//hash_frx:sha256",
        requirement("absl_py"),
        requirement("numpy"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "wots_test",
    size = "small",
    srcs = ["wots_test.py"],
    deps = [
        "//sig_frx/hashbased:adrs",
        "//sig_frx/hashbased:tweakable",
        "//sig_frx/hashbased:wots",
        "@hash_frx//hash_frx:sha256",
        requirement("absl_py"),
        requirement("numpy"),
    ] + GPU_PLUGIN_DEPS,
)
