# Copyright 2026 The sig-frx Authors. SPDX-License-Identifier: Apache-2.0
"""Addresses pack to the byte layout RFC 8391 §2.5 defines.

Word order is the whole content of this module, because getting it wrong is
invisible: a transposed pair yields an implementation that is perfectly
self-consistent and reproduces no published digest. The positions below are read
off §2.5 and asserted as byte offsets rather than through a round trip — a round
trip through our own encoder would agree with itself whatever order it chose.

The other thing pinned here is what this encoder refuses to do. §2.5's prose says
`setType()` zeroes the four words after the type word; the reference implementation
the vectors come from does not, and the vectors follow the reference. So the cases
below require the words a constructor does not name to survive, which is the exact
opposite of what `adrs_test` requires of the FIPS 205 encoder.
"""

from __future__ import annotations

import numpy as np
from absl.testing import absltest

from sig_frx.hashbased import rfc8391_adrs as a
from sig_frx.hashbased.testing import rfc8391_vectors


def _tree_address(words: list[int]) -> int:
    """Words 1 and 2 as the one 64-bit tree address they encode."""
    return (words[1] << 32) | words[2]


def _from_words(words: list[int]) -> a.Adrs:
    """An address with every word set — what the reference's fixture is."""
    return a.Adrs(
        layer=words[0],
        tree=_tree_address(words),
        type=words[3],
        trailing=(words[4], words[5], words[6]),
        key_and_mask=words[7],
    )


class LayoutTest(absltest.TestCase):
    def test_the_encoding_is_thirty_two_bytes(self) -> None:
        self.assertEqual(a.ADRS_SIZE, 32)
        self.assertLen(a.encode(a.ots(1, 2, 3, 4, 5)), 32)

    def test_each_word_lands_where_the_standard_puts_it(self) -> None:
        # Eight uniform four-byte slots, unlike FIPS 205's 4/12/4/4/4/4 — the tree
        # address gets two of them and nothing gets more.
        encoded = a.encode(
            a.Adrs(
                layer=0x11223344,
                tree=0x5566778899AABBCC,
                type=0xDDEEFF00,
                trailing=(0x01020304, 0x05060708, 0x090A0B0C),
                key_and_mask=0x0D0E0F10,
            )
        )
        self.assertEqual(encoded[0:4], bytes.fromhex("11223344"))
        self.assertEqual(encoded[4:8], bytes.fromhex("55667788"))
        self.assertEqual(encoded[8:12], bytes.fromhex("99aabbcc"))
        self.assertEqual(encoded[12:16], bytes.fromhex("ddeeff00"))
        self.assertEqual(encoded[16:20], bytes.fromhex("01020304"))
        self.assertEqual(encoded[20:24], bytes.fromhex("05060708"))
        self.assertEqual(encoded[24:28], bytes.fromhex("090a0b0c"))
        self.assertEqual(encoded[28:32], bytes.fromhex("0d0e0f10"))

    def test_each_type_encodes_its_own_number(self) -> None:
        by_type = {
            a.AdrsType.OTS: a.ots(0, 0, 0, 0, 0),
            a.AdrsType.LTREE: a.ltree(0, 0, 0, 0, 0),
            a.AdrsType.HASH_TREE: a.hash_tree(0, 0, 0, 0),
        }
        self.assertLen(by_type, 3)
        for expected, address in by_type.items():
            self.assertEqual(
                int.from_bytes(a.encode(address)[12:16], "big"),
                int(expected),
                str(expected),
            )

    def test_each_type_names_the_words_the_standard_gives_it(self) -> None:
        # Figures 2, 3 and 4: the three words between the type and `keyAndMask`.
        self.assertEqual(a.ots(0, 0, 3, 5, 7).trailing, (3, 5, 7))
        self.assertEqual(a.ltree(0, 0, 3, 5, 7).trailing, (3, 5, 7))
        # The hash tree address' first of the three is §2.5's padding, which the
        # standard defines as zero rather than leaving to a caller.
        self.assertEqual(a.hash_tree(0, 0, 5, 7).trailing, (0, 5, 7))

    def test_a_word_that_does_not_fit_is_an_error(self) -> None:
        with self.assertRaisesRegex(ValueError, "does not fit"):
            a.encode(a.ots(1 << 32, 0, 0, 0, 0))
        with self.assertRaisesRegex(ValueError, "unsigned"):
            a.encode(a.ots(-1, 0, 0, 0, 0))


class NoNormalizationTest(absltest.TestCase):
    """The words a component does not name survive it.

    §2.5's prose has `setType()` zero the four words after the type word. The
    reference's `set_type` writes `addr[3]` and nothing else, and every published
    vector was generated by the reference — so an encoder that followed the prose
    would compute a different WOTS+ public key for every one of them.
    """

    def test_the_type_is_a_field_and_not_a_closed_set(self) -> None:
        # The fixture's type word is 1500000000, which no scheme produces and no
        # per-type constructor can express. It has to reach the hash anyway.
        fixture = _from_words(rfc8391_vectors.ADDR_WORDS)
        self.assertEqual(int(fixture.type), 500000000 * 3)
        self.assertEqual(int.from_bytes(a.encode(fixture)[12:16], "big"), 500000000 * 3)

    def test_the_fixture_addresses_encode_to_the_reference_bytes(self) -> None:
        # `addr_to_bytes` over the two addresses `test/vectors.c` builds. Both sets
        # produce the same bytes, since the address does not depend on `n`.
        for oid, vectors in rfc8391_vectors.REFERENCE.items():
            with self.subTest(oid=oid):
                self.assertEqual(
                    a.encode(_from_words(rfc8391_vectors.ADDR_WORDS)),
                    vectors.addr_bytes,
                )
                self.assertEqual(
                    a.encode(_from_words(rfc8391_vectors.ADDR2_WORDS)),
                    vectors.addr2_bytes,
                )


class KeyAndMaskTest(absltest.TestCase):
    def test_it_rewrites_only_the_last_word(self) -> None:
        fixture = _from_words(rfc8391_vectors.ADDR_WORDS)
        encoded = a.encode_batch(fixture)
        for value in (0, 1, 2):
            rewritten = a.with_key_and_mask(encoded, value)
            np.testing.assert_array_equal(rewritten[:, :28], encoded[:, :28])
            self.assertEqual(int.from_bytes(bytes(rewritten[0, 28:]), "big"), value)

    def test_it_agrees_with_setting_the_field(self) -> None:
        # The derivation §5.1 does on the encoded bytes has to be the same address
        # as the one built with the field set, or `F` and `H` would tweak with
        # something no constructor can name.
        fixture = _from_words(rfc8391_vectors.ADDR_WORDS)
        for value in (0, 1, 2):
            built = a.encode(
                a.Adrs(
                    fixture.layer,
                    fixture.tree,
                    fixture.type,
                    fixture.trailing,
                    key_and_mask=value,
                )
            )
            self.assertEqual(
                bytes(a.with_key_and_mask(a.encode_batch(fixture), value)[0]), built
            )

    def test_it_leaves_the_caller_s_addresses_alone(self) -> None:
        encoded = a.encode_batch(a.ots(1, 2, 3, 4, 5))
        before = bytes(encoded[0])
        a.with_key_and_mask(encoded, 2)
        self.assertEqual(bytes(encoded[0]), before)

    def test_a_wrongly_sized_address_is_an_error(self) -> None:
        with self.assertRaisesRegex(ValueError, "32 bytes"):
            a.with_key_and_mask(np.zeros((1, 22), dtype=np.uint8), 0)


class ThirdWordTest(absltest.TestCase):
    """The word a WOTS+ chain advances, against encoding the address that holds it."""

    def _chain(self, hash_index: int) -> np.ndarray:
        return np.asarray(a.encode_batch(a.ots(1, 2, 3, np.arange(4), hash_index)))

    def test_it_agrees_with_encoding_the_step(self) -> None:
        for step in (0, 1, 14):
            with self.subTest(step=step):
                np.testing.assert_array_equal(
                    a.with_third_word(self._chain(0), step), self._chain(step)
                )

    def test_it_leaves_keyandmask_and_everything_before_it_alone(self) -> None:
        # The word is in the middle of this layout, unlike FIPS 205's: the hash
        # family sets `keyAndMask` on the address the chain hands it, so a
        # replacement that ran past its own word would undo that.
        encoded = a.with_key_and_mask(self._chain(0), 2)
        rewritten = a.with_third_word(encoded, 6)
        np.testing.assert_array_equal(rewritten[:, :24], encoded[:, :24])
        np.testing.assert_array_equal(rewritten[:, 28:], encoded[:, 28:])
        self.assertEqual(int.from_bytes(bytes(rewritten[0, 24:28]), "big"), 6)


class BatchTest(absltest.TestCase):
    """The batched encoding against the per-address one, word by word.

    `encode_batch` writes a whole batch with array arithmetic while `encode` writes
    one address the way §2.5 spells it out. The second is the reference: it is what
    the cases above pin against the standard, so requiring the two to agree carries
    that agreement over to the form every component calls.
    """

    def _reference(self, addresses: list[a.Adrs]) -> np.ndarray:
        rows = [a.encode(address) for address in addresses]
        return np.frombuffer(b"".join(rows), dtype=np.uint8).reshape(len(rows), 32)

    def test_every_word_can_vary_at_once(self) -> None:
        # Seven columns, all different, so a word written into the wrong slot cannot
        # coincide with the right answer.
        rows = 6
        columns = [np.arange(rows) * (offset + 1) + offset for offset in range(7)]
        batch = a.encode_batch(
            a.Adrs(
                layer=columns[0],
                tree=columns[1],
                type=columns[2],
                trailing=(columns[3], columns[4], columns[5]),
                key_and_mask=columns[6],
            )
        )
        np.testing.assert_array_equal(
            batch,
            self._reference(
                [
                    a.Adrs(
                        int(columns[0][row]),
                        int(columns[1][row]),
                        int(columns[2][row]),
                        (
                            int(columns[3][row]),
                            int(columns[4][row]),
                            int(columns[5][row]),
                        ),
                        int(columns[6][row]),
                    )
                    for row in range(rows)
                ]
            ),
        )

    def test_a_scalar_field_covers_the_whole_batch(self) -> None:
        batch = a.encode_batch(a.ots(2, 9, 1, np.arange(3), 0))
        self.assertEqual(batch.shape, (3, 32))
        for row in range(1, 3):
            np.testing.assert_array_equal(batch[row, :20], batch[0, :20])
            self.assertNotEqual(bytes(batch[row, 20:24]), bytes(batch[0, 20:24]))

    def test_all_scalars_is_a_batch_of_one(self) -> None:
        address = a.ltree(1, 2, 3, 4, 5)
        batch = a.encode_batch(address)
        self.assertEqual(batch.shape, (1, 32))
        self.assertEqual(bytes(batch[0]), a.encode(address))

    def test_a_word_too_wide_for_its_slot_is_an_error(self) -> None:
        with self.assertRaisesRegex(ValueError, "does not fit"):
            a.encode_batch(a.hash_tree(0, 0, 0, np.array([0, 1 << 32])))

    def test_a_negative_word_is_an_error(self) -> None:
        with self.assertRaisesRegex(ValueError, "unsigned"):
            a.encode_batch(a.hash_tree(0, 0, 0, np.array([0, -1])))


if __name__ == "__main__":
    absltest.main()
